version: '3'

networks:
  webappnetwork:
      driver: bridge

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "teams_backend"
    ports:
      - "4193:4193"
      - "9000:9000"
    networks:
      - webappnetwork
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "teams_frontend"
    ports:
      - "3000:3000"
    links:
      - backend
    networks:
      - webappnetwork